### PR TITLE
Fix some deprecated api calls and clippy reports

### PR DESCRIPTION
**Pull request by funArash**
Fixes #
Design discussion issue (if applicable) #

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by lalitb — APPROVED** [review]
Thanks

**Comment by lalitb** [comment]
Can you also remove the exclusion of this project from [Cargo.toml](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/Cargo.toml), so the build can be verified.

**Comment by lalitb** [comment]
@funArash - There are some errors it in CI build for Datadog if you can fix in this PR.  Thanks.

```rust
 Documenting opentelemetry-datadog v0.10.0 (/home/runner/work/opentelemetry-rust-contrib/opentelemetry-rust-contrib/opentelemetry-datadog)
error: unexpected `cfg` condition value: `surf-client`
   --> opentelemetry-datadog/src/exporter/mod.rs:162:21
    |
162 |                 not(feature = "surf-client"),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
    = help: consider adding `surf-client` as a feature in `Cargo.toml`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: `-D unexpected-cfgs` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`

error: unexpected `cfg` condition value: `surf-client`
   --> opentelemetry-datadog/src/exporter/mod.rs:168:17
    |
168 |                 feature = "surf-client"
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
    = help: consider adding `surf-client` as a feature in `Cargo.toml`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration

error: unexpected `cfg` condition value: `surf-client`
   --> opentelemetry-datadog/src/exporter/mod.rs:172:21
    |
172 |                 not(feature = "surf-client"),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
    = help: consider adding `surf-client` as a feature in `Cargo.toml`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration

error: could not document `opentelemetry-datadog`
```

**Comment by funArash** [comment]
> @funArash - There are some errors in CI build for Datadog if you can fix in this PR. Thanks.
> 
> ```rust
>  Documenting opentelemetry-datadog v0.10.0 (/home/runner/work/opentelemetry-rust-contrib/opentelemetry-rust-contrib/opentelemetry-datadog)
> error: unexpected `cfg` condition value: `surf-client`
>    --> opentelemetry-datadog/src/exporter/mod.rs:162:21
>     |
> 162 |                 not(feature = "surf-client"),
>     |                     ^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
>     = help: consider adding `surf-client` as a feature in `Cargo.toml`
>     = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
>     = note: `-D unexpected-cfgs` implied by `-D warnings`
>     = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
> 
> error: unexpected `cfg` condition value: `surf-client`
>    --> opentelemetry-datadog/src/exporter/mod.rs:168:17
>     |
> 168 |                 feature = "surf-client"
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
>     = help: consider adding `surf-client` as a feature in `Cargo.toml`
>     = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> error: unexpected `cfg` condition value: `surf-client`
>    --> opentelemetry-datadog/src/exporter/mod.rs:172:21
>     |
> 172 |                 not(feature = "surf-client"),
>     |                     ^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: expected values for `feature` are: `agent-sampling`, `reqwest`, `reqwest-blocking-client`, `reqwest-client`, and `surf`
>     = help: consider adding `surf-client` as a feature in `Cargo.toml`
>     = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> error: could not document `opentelemetry-datadog`
> ```

I cannot repo the errors locally.. am I missing something?

```
export CARGO_INCREMENTAL=0    
export RUSTDOCFLAGS=-Dwarnings

cargo doc --all-features --no-deps
```

**Comment by funArash** [comment]
found it.. `cargo +nightly doc --all-features --no-deps` reproed the errors

**Pull request merged**
