### PR TITLE
Upgrade eventheader version for userevents exporter for metrics.

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #
Design discussion issue (if applicable) #

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]
changelog would nice as well.

**Comment by lalitb** [comment]
@jtescher  We need a new package for this crate along with the changes in this PR. It would be unfair to ask you to publish every time. Do you think it would be possible to somehow get the publish access to me and @cijothomas at least for [opentelemetry-user-events-metrics](https://crates.io/crates/opentelemetry-user-events-metrics) and [opentelemetry-user-events-logs ](https://crates.io/crates/opentelemetry-user-events-logs) at this time?

**Comment by lalitb** [comment]
> @jtescher We need a new package for this crate. It would be unfair to ask you to publish every time. Do you think it would be possible to somehow get the publish access to me and @cijothomas at least for [opentelemetry-user-events-metrics](https://crates.io/crates/opentelemetry-user-events-metrics) and [opentelemetry-user-events-logs ](https://crates.io/crates/opentelemetry-user-events-logs) at this time?

@jtescher - Gentle ping on this request :)

**Comment by cijothomas** [comment]
> @jtescher We need a new package for this crate. It would be unfair to ask you to publish every time. Do you think it would be possible to somehow get the publish access to me and @cijothomas at least for [opentelemetry-user-events-metrics](https://crates.io/crates/opentelemetry-user-events-metrics) and [opentelemetry-user-events-logs ](https://crates.io/crates/opentelemetry-user-events-logs) at this time?

Got the access. Thank you!

**Pull request merged**
