### PR TITLE
opentelemetry-stackdriver: Update Stackdriver schema

### PR DESCRIPTION
**Pull request by hdost**
This will fix CI.

- Add versioning field.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust/blob/main/CONTRIBUTING.md) guidelines followed
* [x] Unit tests added/updated (if applicable)
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [x] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by lalitb** [comment]
Have removed the stackdriver from the root workspace as of now, as it's build is failing. We can bring it back once fixed.

**Comment by lalitb** [comment]
The CI is not failing anymore without this PR. Are changes still relevant?  
@hdost @djc if anyone knows.

**Comment by djc** [comment]
I don't think this is necessary.

**Comment by lalitb** [comment]
Not relevant anymore.

**Pull request closed without merging**
