### PR TITLE
opentelemetry 0.22 et al updates

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by shaun-cox — APPROVED** [review]
Nice cleanup, thank you.

**Comment by cijothomas** [comment]
@djc @hdost We need changelog entry for the crates before releasing them? I think we need to release all the crates, since we never did a release since moving to contrib..

**Comment by hdost** [comment]
I had that thought after merging we can address during the release of them.

**Comment by cijothomas** [comment]
> I had that thought after merging we can address during the release of them. I'll come through with a cleanup PR so we can get a release ready.

Thanks! That'll also confirm that you have the necessary rights to publish as well.

**Pull request merged**
