### PR TITLE
Prepare for release (with bump to otel-rust v0.25)

### PR DESCRIPTION
**Pull request by lalitb**
Fixes #
Design discussion issue (if applicable) #

## Changes

Please provide a brief description of the changes here.

## Merge requirement checklist

* [ ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/CONTRIBUTING.md) guidelines followed
* [ ] Unit tests added/updated (if applicable)
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Comment by cijothomas** [comment]
@lalitb let me know if you are doing the release for the crates from this repo.
(for next time, we can steal/clone the script from main repo here too)

**Comment by lakaniemi** [comment]
@lalitb for `opentelemetry-datadog`, the `cargo.toml` file does not use `workspace = true` for the dependencies:

```
opentelemetry = { version = "0.24", features = ["trace"] }
opentelemetry_sdk = { version = "0.24", features = ["trace"] }
opentelemetry-http = { version = "0.13" }
```

Doesn't that mean that the datadog package is not updated properly to the newest versions?

**Comment by lalitb** [comment]
> @lalitb let me know if you are doing the release for the crates from this repo. (for next time, we can steal/clone the script from main repo here too)

Yes i will do the release.

**Comment by lalitb** [comment]
> @lalitb for `opentelemetry-datadog`, the `cargo.toml` file does not use `workspace = true` for the dependencies:
> 
> ```
> opentelemetry = { version = "0.24", features = ["trace"] }
> opentelemetry_sdk = { version = "0.24", features = ["trace"] }
> opentelemetry-http = { version = "0.13" }
> ```
> 
> Doesn't that mean that the datadog package is not updated properly to the newest versions?

Yes @lakaniemi , its not in this release. Will look into it separately, i believe it had some issue.

**Comment by tsfotis** [comment]
@lalitb When will these be released to crates.io?

**Comment by lalitb** [comment]
> @lalitb When will these be released to crates.io?

Sorry was travelling. Will do it this week.

**Comment by lalitb** [comment]
All the crates except for opentelemetry-datadog are published now. 
Though we would need a new release now for v0.26 bump : https://github.com/open-telemetry/opentelemetry-rust/pull/2160

**Pull request merged**
