### PR TITLE
Add Code From open-telemetry/opentelemetry-rust

### PR DESCRIPTION
**Pull request by hdost**
We want to preserve code history.

### CODE REVIEW

**Comment by hdost** [comment]
To see the actual changes we want here: https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/2/commits/9e9084b7a7715565f6831146d6771d7a732859d0

**Review by TommyCpp — COMMENTED** [review]
Nice to see this done!

We also need to change the `homepage` and `repository` in the `Cargo.toml` for all crate that's moved to here

**Comment by hdost** [comment]
@TommyCpp Done 👍🏼

**Review by TommyCpp — APPROVED** [review]

**Review by shaun-cox — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
